In [2]:
l = [1,2,3]
print(l)
print(type(l))

[1, 2, 3]
<class 'list'>


In [3]:
import numpy as np
l = np.array(l)
print(l)
print(type(l))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
l= np.array([[1,2,3],[4,5,6]])
print(l, type(l))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [5]:
print(l.shape)

(2, 3)


In [6]:
print(l.ndim)

2


In [7]:
l = np.array((1,2,3))

In [8]:
print(l)

[1 2 3]


In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
l = np.eye(4)

In [16]:
# broadcasting 

l = l*10
print(l)

[[20. 10. 10. 10.]
 [10. 20. 10. 10.]
 [10. 10. 20. 10.]
 [10. 10. 10. 20.]]


In [17]:
np.ones?

In [22]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [26]:
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [32]:
arr = arr.reshape((3,2))
print(arr.shape)

(3, 2)


In [33]:
arr 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
arr.max()

6

In [38]:
arr.max(axis=0)

array([5, 6])

In [39]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

In [46]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [47]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [48]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [49]:
np.hsplit?

In [66]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.concatenate((a,b), 0)

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [71]:
np.random.shuffle(a)
print(a)

[1 2 3 4 5]


In [72]:
np.random.seed(1)
np.random.shuffle(b)
print(b)

[4 2 1 5 3]
